version: '3'

services:
  rest-hapi:
    build: 
      context: .
    container_name: rest-hapi
    command: npm start
    restart: always
    volumes: 
      - ./:/usr/app
    depends_on:
      - rest-hapi-db
    ports:
      - '8000:8000'
          
  rest-hapi-db:
    image: mongo:latest
    container_name: rest-hapi-db
    volumes:
      - rest-hapi-db:/data/db
    ports: 
      - '27017:27017'

volumes: 
  rest-hapi-db:
